In [1]:
import numpy as np
import pandas as pd

In [3]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type

arr=np.array([0,1,2,3,4,5])
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
# 2. Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])

arr.dtype

dtype('float64')

In [9]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers
arr=np.array([2+3j, 5-9j, 1-99j])

arr.dtype

dtype('complex128')

In [15]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.
arr=np.array([0,1,2,3,4,5])
arr.astype(np.float32)

array([0., 1., 2., 3., 4., 5.], dtype=float32)

In [17]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.5, 2.6, 3.7], dtype=np.float64)

arr_float32 = arr.astype(np.float32)
arr_float32

array([1.5, 2.6, 3.7], dtype=float32)

In [24]:
# 6 Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

def array_attributes(arr):
    result={'Shape':arr.shape, 'Size':arr.size, 'Data Type':arr.dtype}
    return result

arr=np.array([0,1,2,3,4,5])
array_attributes(arr)

{'Shape': (6,), 'Size': 6, 'Data Type': dtype('int64')}

In [29]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionalit

def array_dimension(arr):
    return arr.ndim
arr=np.array([0,1,2,3,4,5])
array_dimension(arr)

1

In [30]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
# size in bytes.

def item_size_info(arr):
    item_size=arr.itemsize
    total_size=arr.nbytes
    return item_size, total_size
arr=np.array([0,1,2,3,4,5])
item_size_info(arr)

(8, 48)

In [31]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):
    return arr.strides

arr=np.array([0,1,2,3,4,5])
array_strides(arr)

(8,)

In [32]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
# and strides of the arra

def shape_stride_relationship(arr):
    sh=arr.shape
    st=arr.strides
    return sh,st

arr=np.array([0,1,2,3,4,5])
shape_stride_relationship(arr)

((6,), (8,))

In [37]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
# zeros with `n` elements.

def create_zeros_array(n):
    return np.zeros(n)

create_zeros_array(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
# NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(rows,cols):
     return np.ones((rows, cols))

mat=create_ones_matrix(3,3)
print(mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [52]:
#13 . Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
# creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
# `step`.

def generate_range_array(start, stop, step):
    ar=np.arange(start,stop, step)
    return ar
generate_range_array(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [54]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
# arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
# (inclusive).

def generate_linear_space(start,stop,num):
    return np.arange(start,stop,num)

generate_linear_space(1.5, 30.0, 2)

array([ 1.5,  3.5,  5.5,  7.5,  9.5, 11.5, 13.5, 15.5, 17.5, 19.5, 21.5,
       23.5, 25.5, 27.5, 29.5])

In [55]:
# 15 Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
# identity matrix of size `n x n` using `numpy.eye`

def create_identity_matrix(n):
    return np.eye(n)
create_identity_matrix(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
# 16. Write a function that takes a Python list and converts it into a NumPy array

l=[1,3,4,5,6,7,8]

arr=np.array(l)
arr

array([1, 3, 4, 5, 6, 7, 8])

In [68]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
# same data.

l=[1,3,4,5,6,7,8]

arr=np.array(l)
ar2=arr.view()
ar2

array([1, 3, 4, 5, 6, 7, 8])

In [71]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def arr_concatenate(ar1,ar2):
    ar3=np.concatenate((ar1,ar2),axis=0)
    return ar3

ar1=np.array([1,2,3])
ar2=np.array([4,5,6])
arr_concatenate(ar1,ar2)

array([1, 2, 3, 4, 5, 6])

In [77]:
# 19 # Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
# concatenate`.

ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[11],[61]])

np.concatenate((ar1,ar2), axis=1)

array([[ 1,  2,  3, 11],
       [ 4,  5,  6, 61]])

In [78]:
# 20  Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertical_stack(arrays):
    return np.vstack(arrays)


arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])
arr3 = np.array([[7, 8, 9]])

arrays = [arr1, arr2, arr3]

result = vertical_stack(arrays)
print("Vertically stacked array:\n", result)

Vertically stacked array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [81]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
# with a given step size.

def int_array(start,stop,step):
    return np.arange(start,stop+1,step)
int_array(0,10,2)

array([ 0,  2,  4,  6,  8, 10])

In [84]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def zero_to_one(start,stop,step):
    return np.linspace(start,stop,step)
zero_to_one(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [85]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
# 1000 (inclusive).

def log_space_array(start,stop,step):
    return np.logspace(start,stop,step)
log_space_array(1,1000,5)

/opt/conda/lib/python3.10/site-packages/numpy/core/function_base.py:277: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [88]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
# are random integers between 1 and 100.

data = np.random.randint(1, 101, size=(5, 3))
df=pd.DataFrame(data)
df

0   1   2
0   5  41  60
1  23  21  52
2  56  15  32
3  49  20  34
4  42   8  29

In [92]:
 #25 Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
# with zeros. Use NumPy operations within the Pandas DataFrame

df=pd.DataFrame({
    'c1':[1,-2,3,-4,5],
    'cl2':[1,-2,3,-4,5],
    'cl3':[1,-2,3,-4,5]
})

def remove_neg(df,col):
    df[col]=df[col].apply(lambda x:0 if x<0 else x)
    return df

remove_neg(df,'cl3')
    

c1  cl2  cl3
0   1    1    1
1  -2   -2    0
2   3    3    3
3  -4   -4    0
4   5    5    5

In [93]:
# 26 Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [94]:
# 27 Retrieve the element at index (1, 2) from the 2D NumPy arr

arr_2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

arr_2d[1][2]

6

In [103]:
# 28  Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])

for i in arr:
    if i>5:
        print(i)

8
10
7


In [105]:
# 29 Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

ar2=arr[2:6]
ar2

array([3, 4, 5, 6])

In [114]:
# 30 Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

ar2=arr_2d[0:2, 1:3]
ar2

array([[2, 3],
       [5, 6]])

In [115]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices
# provided in another a

def extract_elements(arr, indices):

    extracted_elements = np.array([arr[row, col] for row, col in indices])
    return extracted_elements


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = [(0, 1), (1, 2), (2, 0)]

result = extract_elements(arr, indices)
print(result)  


[2 6 7]


In [116]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing


def filter_elements(arr, threshold):
    filtered_elements = arr[arr > threshold]
    return filtered_elements

# Example usage:
arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5

result = filter_elements(arr, threshold)
print(result)  


[ 8 10  7]


In [119]:
#35# Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
    

def extract_elements(arr, row_indices, col_indices):

    extracted_elements = arr[row_indices, col_indices]
    return extracted_elements

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

result = extract_elements(arr, row_indices, col_indices)
print(result)  


[2 6 7]


In [4]:
# 37 Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
# corresponding element in arr1 using NumPy broadcasting.

import numpy as np
import pandas as pd

arr1=np.array([1,2,3])
arr2=np.array([[1,1,1,1],[5,5,5,5],[9,9,9,9]])

arr1@arr2

array([38, 38, 38, 38])

In [9]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting

arr1=np.array([1,2,3])
arr2=np.array([[1,1,1],[5,5,5],[9,9,9],[2,2,2]])

arr1+arr2

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [ 3,  4,  5]])

In [10]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1=np.array([[1],[1],[1]])
arr2=np.array([1,2,3])

arr1+arr2

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [11]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1=np.array([[1,1,1],[5,5,5]])
arr2=np.array([[5,5],[9,9]])

arr2@arr1

array([[30, 30, 30],
       [54, 54, 54]])

In [12]:
# 41. Calculate column-wise mean for the given array

arr = np.array([[1, 2, 3], [4, 5, 6]])

np.mean(arr, axis=0)

array([2.5, 3.5, 4.5])

In [13]:
# 42. Find maximum value in each row of the given array
arr = np.array([[1, 2, 3], [4, 5, 6]])

np.max(arr, axis=1)

array([3, 6])

In [14]:
# 3. For the given array, find indices of maximum value in each column
arr = np.array([[1, 2, 3], [4, 5, 6]])

np.max(arr, axis=0)

array([4, 5, 6])

In [15]:
# 44. For the given array, apply custom function to calculate moving sum along rows.


def moving_sum(arr):
    result = np.zeros_like(arr)
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1]):
            result[i, j] = np.sum(arr[i, :j+1])
    return result


arr = np.array([[1, 2, 3], [4, 5, 6]])

# Apply the custom function
moving_sum_result = moving_sum(arr)
print(moving_sum_result)



[[ 1  3  6]
 [ 4  9 15]]


In [16]:
# 45. In the given array, check if all elements in each column are even

arr = np.array([[2, 4, 6], [3, 5, 7]])

all_even_columns = np.all(arr % 2 == 0, axis=0)
print(all_even_columns)

[False False False]


In [17]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]



def insert_and_delete_elements(arr, insert_indices, insert_values, delete_indices):
    # Insert elements
    for index, value in zip(insert_indices, insert_values):
        arr = np.insert(arr, index, value)
    
    # Delete elements
    arr = np.delete(arr, delete_indices)
    
    return arr


# Apply the function
result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)


[ 1 10 11  4  5]


In [27]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
# Perform element-wise addition between `arr1` and `arr2`.

arr1=np.random.randint(1,100, size=10)
arr2=np.array([1,2,3,4,5,6,7,8,9,10])

arr1+arr2

array([27, 65, 17, 36, 85, 87, 88, 11, 84, 52])

In [28]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
# from 1 to 10. Subtract `arr2` from `arr1` element-wise

arr2=np.array([10,9,8,7,6,5,4,3,2,1])
arr2=np.array([1,2,3,4,5,6,7,8,9,10])

arr1-arr2

array([25, 61, 11, 28, 75, 75, 74, -5, 66, 32])

In [30]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
# Perform element-wise multiplication between `arr1` and `arr2`

arr1=np.random.randint(1,10, size=5)
arr2=np.array([1,2,3,4,5])

arr1*arr2

array([ 8, 14,  3, 36, 20])

In [31]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
# to 5. Perform element-wise division of `arr1` by `arr2`

arr1=np.array([2,4,6,8,10])
arr2=np.array([1,2,3,4,5])

arr1/arr2

array([2., 2., 2., 2., 2.])

In [32]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
# reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

arr1=np.array([1,2,3,4,5])
arr2=np.array([5,4,3,2,1])

arr1**arr2

array([ 1, 16, 27, 16,  5])

In [33]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

def count_occ(arr,key):
    occ=0
    for i in arr:
        if i==key:
            occ+=1
    return occ

count_occ(arr, 'world')

1

In [39]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

np.char.add(arr1,arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [46]:
# 60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def len_element(arr):
    m=''
    for i in arr:
        if len(i)>len(m):
            m=i
    return len(m)
len_element(arr)

9

In [59]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
# standard deviation of the dataset using NumPy's functions.

nums=np.random.randint(1,1000, size=100)
df=pd.DataFrame({
    'nums':nums})
print('mean: ',df.mean())
print('median: ',df.median())
print('Variance: ',df.var())
print('Standard Deviation: ',df.std())

mean:  nums    527.37
dtype: float64
median:  nums    549.0
dtype: float64
Variance:  nums    77155.144545
dtype: float64
Standard Deviation:  nums    277.768149
dtype: float64


In [64]:
# . Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
# percentiles along with the first and third quartiles

arr=np.random.randint(10,1000,size=50)
print(np.percentile(arr,10))
print(np.percentile(arr,50))
print(np.percentile(arr,90))

print(np.percentile(arr,25))
print(np.percentile(arr,75))

71.2
564.0
910.9
215.0
745.5


In [67]:
# Create a NumPy array of integers and find the index of a specific element.

arr1=np.array([5,4,3,2,1])
np.where(arr1==4)

(array([1]),)

In [69]:
# Filter elements >20 in the given NumPy array

arr = np.array([12, 25, 6, 42, 8, 30])
ar2=arr[arr>20]
ar2

array([25, 42, 30])

In [84]:
# Filter elements which are divisible by 3 from a given NumPy array

arr = np.array([1, 5, 8, 12, 15])
ar2=arr[(arr%3)==0]
ar2

array([12, 15])

In [83]:
# Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array

arr = np.array([10, 20, 30, 40, 50])
ar2=arr[arr>=20]
ar2=ar2[ar2<=40]
ar2

array([20, 30, 40])

In [85]:
# For the given NumPy array, check its byte order using the `dtype` attribute byteorder

arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [86]:
# For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [87]:
 # For the given NumPy array, swap its byte order without modifying the original array using
# `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype=int32)

In [88]:
# Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.


matrix = np.random.randint(1, 100, size=(3, 3))

view_slice = matrix[1:, 1:]


view_slice[0, 0] = 999

print("Original matrix after modification:")
print(matrix)
print("View slice after modification:")
print(view_slice)


Original matrix after modification:
[[ 43  98  40]
 [ 70 999  42]
 [ 79  16  23]]
View slice after modification:
[[999  42]
 [ 16  23]]


In [90]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

A = np.random.randint(1, 100, size=(3, 3))
B = np.random.randint(1, 100, size=(3, 3))

print(A+B)
print(A-B)

[[151  46 100]
 [ 64  78 115]
 [105  65 179]]
[[ 41   2 -54]
 [-30 -14 -81]
 [ 23   9   7]]


In [91]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.random.randint(1, 100, size=(3, 2))
D = np.random.randint(1, 100, size=(2, 4))

C@D

array([[6198, 4548, 4359, 5996],
       [4916, 2372, 4499, 6846],
       [8134, 5572, 6055, 8540]])

In [92]:
# 83. Create a matrix `E` and find its transpose

E = np.random.randint(1, 100, size=(4, 4))

E.T

array([[15, 53, 13, 32],
       [23, 70, 75, 71],
       [36, 53, 88, 18],
       [ 8, 14, 99, 51]])

In [95]:
# 84. Generate a square matrix `F` and compute its determinant.

F = np.random.randint(1, 100, size=(4, 4))
det=np.linalg.det(F)
det

-4255937.000000006

In [96]:
# 85. Create a square matrix `G` and find its inverse.

G = np.random.randint(1, 100, size=(4, 4))

inverse=np.linalg.inv(G)
inverse

array([[-0.00106387,  0.05128074, -0.00280255, -0.01378118],
       [ 0.00481682, -0.01362074,  0.01116637, -0.00482371],
       [-0.00805971,  0.01608208, -0.00052513,  0.00978623],
       [ 0.01031598, -0.03295405, -0.00845202,  0.01068651]])