In [2]:
# 1. Implement a Kalman Filter to predict and update the state of an object given its measurements

import numpy as np

class KalmanFilter:
    def __init__(self, initial_state, initial_covariance, transition_matrix, control_matrix, measurement_matrix, process_noise, measurement_noise):
        self.state = initial_state
        self.covariance = initial_covariance
        self.F = transition_matrix
        self.B = control_matrix
        self.H = measurement_matrix
        self.Q = process_noise
        self.R = measurement_noise

    def predict(self, control_vector):
        self.state = np.dot(self.F, self.state) + np.dot(self.B, control_vector)
        self.covariance = np.dot(np.dot(self.F, self.covariance), self.F.T) + self.Q

    def update(self, measurement):
        y = measurement - np.dot(self.H, self.state)
        S = np.dot(self.H, np.dot(self.covariance, self.H.T)) + self.R
        K = np.dot(np.dot(self.covariance, self.H.T), np.linalg.inv(S))
        self.state = self.state + np.dot(K, y)
        self.covariance = self.covariance - np.dot(np.dot(K, self.H), self.covariance)

# Example usage
initial_state = np.array([0, 0])
initial_covariance = np.eye(2)
transition_matrix = np.eye(2)
control_matrix = np.eye(2)
measurement_matrix = np.eye(2)
process_noise = np.eye(2) * 0.01
measurement_noise = np.eye(2) * 0.1

kf = KalmanFilter(initial_state, initial_covariance, transition_matrix, control_matrix, measurement_matrix, process_noise, measurement_noise)
kf.predict(np.array([1, 1]))
kf.update(np.array([1.2, 0.9]))
print("Predicted state:", kf.state)


Predicted state: [1.18198198 0.90900901]


In [1]:
# 2. Write a function to normalize an image array such that pixel values are scaled between 0 and 1

import numpy as np

def normalize_image(image_array):
    normalized_image = image_array / 255.0
    return normalized_image

# Example usage
image_array = np.random.randint(0, 256, (5, 5, 3))  # Dummy image array
normalized_image = normalize_image(image_array)
print("Normalized Image Array:", normalized_image)


Normalized Image Array: [[[0.55686275 0.96862745 0.79215686]
  [0.09411765 0.19215686 0.98431373]
  [0.33333333 0.49803922 0.04313725]
  [0.38039216 0.45882353 0.58823529]
  [0.63137255 0.65882353 0.33333333]]

 [[0.14117647 0.76078431 0.65098039]
  [0.57647059 0.96078431 0.33333333]
  [0.20392157 0.07058824 0.83137255]
  [0.05882353 0.08235294 0.90980392]
  [0.43137255 0.24313725 0.02745098]]

 [[0.79215686 0.36078431 0.77647059]
  [0.85490196 0.89019608 0.60392157]
  [0.21176471 0.41176471 0.06666667]
  [0.64313725 0.24705882 0.6745098 ]
  [0.31372549 0.12941176 0.44313725]]

 [[0.17647059 0.35686275 0.17647059]
  [0.70588235 0.41176471 0.25098039]
  [0.98431373 0.69019608 0.90980392]
  [0.29803922 0.48235294 0.50980392]
  [0.20784314 0.63529412 0.58823529]]

 [[0.49019608 0.54509804 0.11764706]
  [0.51372549 0.24705882 0.01568627]
  [0.96862745 0.22352941 0.90588235]
  [0.76470588 0.63921569 0.82745098]
  [0.70196078 0.29411765 0.34509804]]]


In [3]:
# 3. Create a function to generate dummy object detection data with confidence scores and bounding boxes. Filter the detections based on a confidence threshold

import numpy as np

def generate_dummy_detections(num_detections):
    detections = []
    for _ in range(num_detections):
        confidence = np.random.rand()
        bbox = np.random.randint(0, 100, 4)
        detections.append((confidence, bbox))
    return detections

def filter_detections(detections, threshold):
    filtered = [d for d in detections if d[0] >= threshold]
    return filtered

# Example usage
detections = generate_dummy_detections(10)
filtered_detections = filter_detections(detections, 0.5)
print("Filtered Detections:", filtered_detections)


Filtered Detections: [(0.7252281780520584, array([98, 68, 38, 47])), (0.7650665968532852, array([23, 72, 94, 17])), (0.8403416323767811, array([15, 78, 18, 62])), (0.9659892152391645, array([ 5, 31,  9, 89]))]


In [4]:
# 4. Write a function that takes a list of YOLO detections and extracts a random 128-dimensional feature vector for each detection

import numpy as np

def extract_feature_vectors(detections, vector_size=128):
    feature_vectors = []
    for detection in detections:
        feature_vector = np.random.rand(vector_size)
        feature_vectors.append(feature_vector)
    return feature_vectors

# Example usage
yolo_detections = [(0.9, [30, 50, 100, 150]), (0.8, [20, 40, 80, 120])]  # Dummy detections
features = extract_feature_vectors(yolo_detections)
print("Extracted Feature Vectors:", features)


Extracted Feature Vectors: [array([0.77107677, 0.18621433, 0.8587716 , 0.34054595, 0.21015961,
       0.81497596, 0.89863951, 0.96047108, 0.94330969, 0.28468042,
       0.04118648, 0.32356561, 0.19328491, 0.9839799 , 0.54935025,
       0.68812504, 0.18176681, 0.61478053, 0.96623356, 0.03328301,
       0.66012899, 0.14888434, 0.55016272, 0.93800822, 0.03325207,
       0.02635425, 0.69113365, 0.98721261, 0.53729229, 0.57840906,
       0.63780835, 0.09098149, 0.52595282, 0.41268906, 0.49067973,
       0.87458148, 0.33636592, 0.48239151, 0.23639992, 0.64488138,
       0.12513302, 0.95227587, 0.76931399, 0.73512179, 0.44953929,
       0.52661499, 0.55879652, 0.07728911, 0.23047823, 0.14142729,
       0.27435337, 0.23391251, 0.79610792, 0.93274759, 0.48453284,
       0.51549677, 0.83147046, 0.1162717 , 0.39042776, 0.18354472,
       0.82793552, 0.71591781, 0.74686303, 0.05982961, 0.1202318 ,
       0.78198731, 0.75219053, 0.37678913, 0.79768686, 0.67540903,
       0.02116318, 0.03723438, 0.6

In [5]:
# 5. Write a function to re-identify objects by matching feature vectors based on Euclidean distance

import numpy as np

def reidentify_objects(feature_vectors1, feature_vectors2):
    distances = np.zeros((len(feature_vectors1), len(feature_vectors2)))
    for i, fv1 in enumerate(feature_vectors1):
        for j, fv2 in enumerate(feature_vectors2):
            distances[i, j] = np.linalg.norm(fv1 - fv2)
    matches = []
    for i in range(len(feature_vectors1)):
        j = np.argmin(distances[i])
        matches.append((i, j))
    return matches

# Example usage
features1 = extract_feature_vectors(yolo_detections)
features2 = extract_feature_vectors(yolo_detections)
matches = reidentify_objects(features1, features2)
print("Matches:", matches)


Matches: [(0, 1), (1, 0)]


In [ ]:
# 6. Write a function to track object positions using YOLO detections and a Kalman Filter


import numpy as np

class KalmanFilter:
    def __init__(self, state, covariance, transition_matrix, control_matrix, measurement_matrix, process_noise, measurement_noise):
        self.state = state
        self.covariance = covariance
        self.F = transition_matrix
        self.B = control_matrix
        self.H = measurement_matrix
        self.Q = process_noise
        self.R = measurement_noise

    def predict(self, control_vector):
        self.state = np.dot(self.F, self.state) + np.dot(self.B, control_vector)
        self.covariance = np.dot(np.dot(self.F, self.covariance), self.F.T) + self.Q

    def update(self, measurement):
        y = measurement - np.dot(self.H, self.state)
        S = np.dot(self.H, np.dot(self.covariance, self.H.T)) + self.R
        K = np.dot(np.dot(self.covariance, self.H.T), np.linalg.inv(S))
        self.state = self.state + np.dot(K, y)
        self.covariance = self.covariance - np.dot(np.dot(K, self.H), self.covariance)

def track_objects(detections, kalman_filters):
    for detection in detections:
        for kf in kalman_filters:
            kf.predict(np.array([0, 0]))  # No control input
            kf.update(np.array(detection[1]))  # Update with detection
    tracked_positions = [kf.state for kf in kalman_filters]
    return tracked_positions

# Example usage
kf1 = KalmanFilter(np.array([0, 0]), np.eye(2), np.eye(2), np.eye(2), np.eye(2), np.eye(2) * 0.01, np.eye(2) * 0.1)
kf2 = KalmanFilter(np.array([0, 0]), np.eye(2), np.eye(2), np.eye(2), np.eye(2), np.eye(2) * 0.01, np.eye(2) * 0.1)
kalman_filters = [kf1, kf2]
tracked_positions = track_objects(yolo_detections, kalman_filters)
print("Tracked Positions:", tracked_positions)


In [ ]:
# 7. Implement a simple Kalman Filter to track an object's position in a 2D space (simulate the object's movement with random noise)

import numpy as np

class SimpleKalmanFilter:
    def __init__(self, state, covariance, transition_matrix, measurement_matrix, process_noise, measurement_noise):
        self.state = state
        self.covariance = covariance
        self.F = transition_matrix
        self.H = measurement_matrix
        self.Q = process_noise
        self.R = measurement_noise

    def predict(self):
        self.state = np.dot(self.F, self.state)
        self.covariance = np.dot(np.dot(self.F, self.covariance), self.F.T) + self.Q

    def update(self, measurement):
        y = measurement - np.dot(self.H, self.state)
        S = np.dot(self.H, np.dot(self.covariance, self.H.T)) + self.R
        K = np.dot(np.dot(self.covariance, self.H.T), np.linalg.inv(S))
        self.state = self.state + np.dot(K, y)
        self.covariance = self.covariance - np.dot(np.dot(K, self.H), self.covariance)

# Simulate object movement with random noise
num_steps = 50
true_position = np.array([0, 0])
positions = [true_position.copy()]
measurements = []

for _ in range(num_steps):
    true_position += np.random.normal(0, 1, size=2)
    measurement = true_position + np.random.normal(0, 1, size=2)
    positions.append(true_position.copy())
    measurements.append(measurement)

# Kalman Filter
kf = SimpleKalmanFilter(np.array([0, 0]), np.eye(2), np.eye(2), np.eye(2), np.eye(2) * 0.01, np.eye(2) * 0.1)

estimated_positions = []
for measurement in measurements:
    kf.predict()
    kf.update(measurement)
    estimated_positions.append(kf.state.copy())

print("True Positions:", positions)
print("Estimated Positions:", estimated_positions)
